export const DATA_TYPES = [
  { key: 'heart', icon: 'heart', label: '심박수', inputMode: 'active' },
  { key: 'blood', icon: 'water', label: '혈압', inputMode: 'active' },
  { key: 'temp', icon: 'thermometer', label: '체온', inputMode: 'active' },
  { key: 'weight', icon: 'scale', label: '체중', inputMode: 'manual' },
  { key: 'sleep', icon: 'moon', label: '수면', inputMode: 'manual' },
  { key: 'step', icon: 'walk', label: '걸음수', inputMode: 'active' },
  { key: 'glucose', icon: 'fitness', label: '혈당', inputMode: 'manual' },
  { key: 'oxygen', icon: 'pulse', label: '산소포화도', inputMode: 'active' },
  { key: 'stress', icon: 'flash', label: '스트레스', inputMode: 'active' },
  { key: 'ecg', icon: 'pulse', label: '심전도', inputMode: 'active' },
  { key: 'spo2', icon: 'pulse', label: 'SpO2', inputMode: 'active' },
  { key: 'activity', icon: 'walk', label: '활동량', inputMode: 'active' },
];

export const METRIC_INFO = [
  {
    key: 'heart',
    icon: 'heart',
    label: '심박수',
    unit: 'bpm',
    category: 'vital',
    normalRange: { min: 60, max: 100 },
  },
  {
    key: 'blood',
    icon: 'water',
    label: '혈압',
    unit: 'mmHg',
    category: 'vital',
    normalRange: { min: 90, max: 120 },
  },
  {
    key: 'temp',
    icon: 'thermometer',
    label: '체온',
    unit: '°C',
    category: 'vital',
    normalRange: { min: 36.1, max: 37.2 },
  },
  {
    key: 'weight',
    icon: 'scale',
    label: '체중',
    unit: 'kg',
    category: 'body',
    normalRange: { min: 45, max: 100 },
  },
  {
    key: 'sleep',
    icon: 'moon',
    label: '수면',
    unit: '시간',
    category: 'activity',
    normalRange: { min: 7, max: 9 },
  },
  {
    key: 'step',
    icon: 'walk',
    label: '걸음수',
    unit: '걸음',
    category: 'activity',
    normalRange: { min: 8000, max: 12000 },
  },
  {
    key: 'glucose',
    icon: 'fitness',
    label: '혈당',
    unit: 'mg/dL',
    category: 'blood',
    normalRange: { min: 70, max: 140 },
  },
  {
    key: 'oxygen',
    icon: 'pulse',
    label: '산소포화도',
    unit: '%',
    category: 'vital',
    normalRange: { min: 95, max: 100 },
  },
  {
    key: 'stress',
    icon: 'flash',
    label: '스트레스',
    unit: '점',
    category: 'stress',
    normalRange: { min: 0, max: 100 },
  },
  {
    key: 'ecg',
    icon: 'pulse',
    label: '심전도',
    unit: 'mV',
    category: 'vital',
    normalRange: { min: -0.5, max: 0.5 },
  },
  {
    key: 'spo2',
    icon: 'pulse',
    label: 'SpO2',
    unit: '%',
    category: 'vital',
    normalRange: { min: 95, max: 100 },
  },
  {
    key: 'activity',
    icon: 'walk',
    label: '활동량',
    unit: 'kcal',
    category: 'activity',
    normalRange: { min: 0, max: 5000 },
  },
]; 